apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "0123456789.dkr.ecr.ap-northeast-1.amazonaws.com/sample:68bed80"
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 256m
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 256Mi
          ports:
            - name: task
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 2
