name: release
on:
  release:
    types: [published]

env:
  PIPELINE_ENDPOINT: https://25wi33suvqq3hbtm6fm2d5k3qe0vdhii.lambda-url.ap-northeast-1.on.aws/
jobs:
  pipeline:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: get tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: install curl
        run: sudo apt-get install -y curl
      - name: send request
        run: |
          curl -H 'content-type: application/json' \
          -d "{\"repository\": \"${{ github.repository }}\", \"tag\": \"${{ env.TAG }}\", \"is_webhook\": true}" \
          ${{ env.PIPELINE_ENDPOINT }}